#
# This file might sound important but...
# It is only used by the hosting on GitHub Pages, it has no other importance to the project
#

title: 'KubeView 2'
remote_theme: benc-uk/theme-msdark
favicon: public/img/icon.png
buttons:
  - b0:
    text: Main Docs
    href: /
  - b3:
    text: Helm
    href: /deploy/helm
