apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  completions: 4
  parallelism: 2
  template:
    spec:
      containers:
        - name: pi
          image: perl:5.34.0
          command: ['perl', 'ZZZZZZZZZZZZ-Mbignum=bpi', '-wle', 'print bpi(2000)']
      restartPolicy: Never
  backoffLimit: 4
