name: CI Lint & Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci-job:
    name: Lint & Build Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Run lint
        run: make lint

      - name: Run generate
        run: make generate

      - name: Run build
        run: make build
